//PORT TO RUN NODEJS SERVER ON
const PORT = 3001

//CSV FILE READING SETUP
const LINESKIP = 2
const CSVFILENAME = 'readcsv.csv'

//FILE AND IMAGE SETUP INFO
const FILENAME = 'chart.png'
const DOTFILENAME = 'dot.png'
const ROOTPOS = [576, 756]
const LEFTEXTREME = [120, 290]
const RIGHTEXTREME = [1028, 299]
const DOTSIZE = [9, 9]

//DATA SETUP INFO
const MAXMAGNITUDE = 12000
const MINANG = 16
const MAXANG = 12

module.exports = {
  PORT,
  FILENAME, DOTSIZE, DOTFILENAME, ROOTPOS, LEFTEXTREME, RIGHTEXTREME,
  MAXMAGNITUDE, MINANG, MAXANG,
  LINESKIP, CSVFILENAME
}